	
VERSION="2.0.0" 
 
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015" 
 
ACCOUNTS=[ 
"GAHHULDPDVGB5WS5PH7BCGLJ7ZHECDBIIMKB62UPVDUOCHNFL7HX3FS7","GBPE7L6AMFQL2IGCVD36VVWZR5DDLINLETF2QMBAJG7ZA65MK7WI4BPK"
] 

[[CURRENCIES]] 
code="ACT" 
issuer="GAHHULDPDVGB5WS5PH7BCGLJ7ZHECDBIIMKB62UPVDUOCHNFL7HX3FS7"
display_decimals="5"
is_asset_anchored=false 
name="Authentic-Payment Community Token" 
desc="We have introduced the Authentic-Payment Community Token ($ACT) to support our ecosystem and the #StellarFamily as well as our other partners. We believe in the power of community, that's why ACT enables an Earn-Fi economy that rewards users for their contributions and encourages them to be active participants and supporters in our ecosystem." 
conditions="$ACT is a 20 million max supply community token created by Authentic-Payment.com, grab your share of the 80k monthly $ACT inflation by supporting and growing the ecosystem"
image="https://authentic-payment.com/wp-content/uploads/2023/01/IMG_1156.png" 
status="live"

[[PRINCIPALS]]
email="support@authentic-payment.com"
twitter="@officialapay"
telegram="https://t.me/EarnACT"
  
# Home Domain:authentic-payment.com 
# $Authentic-Payment
# $Apay $AXLM $ACT
